# The script analyzes corona exposure as a function of time.
# The idea is to see if the number of reported exposures decreases as the govenment is strengthenin the lockdown.

library(tidyverse)
library(lubridate)
# Read the data ----
exposure_files_raw <- dir("data/", pattern = "* Corona exposure locations.csv", full.names = T) %>% 
  map_df(read_csv) %>% 
  janitor::clean_names() %>% 
  rename(location_type = `סוג_מיקום`,
         hours = `שעות_שהייה`,
         exposure_date = `תאריך`,
         comments = `הערות`,
         location_description = `מקום`,
         patient = `שם_חולה`) %>% 
  distinct() %>% 
  mutate(exposure_date = as.POSIXct(exposure_date, tz = "GMT+2", format = "%d/%m/%Y")) %>% 
  mutate(hours = str_replace_all(hours, fixed(" - "), "-")) %>% 
  separate(hours, into = c("start_time", "end_time"), sep = "-") %>% 
  mutate_at(vars(contains("_time")), ~{paste0(., ":00") %>% hms::as_hms(.)}) %>% 
  mutate(exposure_duration = end_time - start_time) %>% 
  mutate(exposure_duration = ifelse(exposure_duration < 0, exposure_duration + 24*60*60, exposure_duration)) %>% 
  mutate(exposure_start = exposure_date + start_time) %>% 
  mutate(exposure_end = exposure_start + exposure_duration)


# Government actions ------------------------------------------------------

gov_actions <- tribble(~decision_date, ~description,
                       "2020-03-12", "Shutdown schools",
                       "2020-03-15", "Kindergarden",
                       "2020-03-16", "Initiating soft lockdown",
                       "2020-03-22", "Hardening the lockdown (up to 10 persons per business. not sure about exact date")
  

# Read the number of confirmed cases from the Johns Hopkins repository ----
global_confirmed_ts <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv") %>% 
  janitor::clean_names() %>% 
  filter(country_region == "Israel") %>% 
  pivot_longer(cols = contains("x"), names_to = "date", values_to = "confirmed")

israel_ts <- global_confirmed_ts %>% 
  mutate(date = str_replace(date, "x", "")) %>% 
  mutate(date = as.POSIXct(date, tz = "GMT+2", format = "%m_%d_%y")) %>% 
  select(date, confirmed)

# Join the data ratio of documented exposures versus #cases -----------------------------------

exposure_vs_confirmed <- exposure_files_raw %>% 
  count(exposure_date, name = "n_documented_exposures") %>% 
  left_join(israel_ts, by = c("exposure_date" = "date")) %>% 
  mutate(ratio_exposure_confirmed = n_documented_exposures/confirmed)

ggplot(exposure_vs_confirmed, aes(x = exposure_date, y = ratio_exposure_confirmed)) + 
  geom_line() + 
  geom_point() +
  xlab("Date") + 
  ylab("Ratio\nExposures/#cases") +
  saridr::theme_sarid() +
  labs(caption = "Data source: MOH GIS tracker @ bit.ly/corona_il\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") + 
  ggtitle("Ratio of documented exposures to the total number of confirmed cases",
          subtitle = "Labels indicate the overall number of confirmed cases") + 
  ggrepel::geom_label_repel(aes(label = confirmed), alpha = 0.5)

# Duration of exposure ----------------------------------------------------

ggplot(exposure_files_raw, aes(y = exposure_duration/60, 
                               x = factor(exposure_date))) + 
  geom_boxplot() +
  saridr::theme_sarid() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(caption = "Data source: MOH GIS tracker @ bit.ly/corona_il\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") + 
  ggtitle("Ratio of documented exposures to the total number of confirmed cases",
          subtitle = "Labels indicate the overall number of confirmed cases") + 
  xlab("") + 
  ylab("Exposure Duration [minutes]")

exposure_files_raw %>% 
  group_by(exposure_date) %>% 
  summarize(median = median(exposure_duration, na.rm = T),
            mean = mean(exposure_duration, na.rm = T),
            n = n()) %>% 
  pivot_longer(c(median, mean), names_to = "type", values_to = "value") %>% 
  ggplot(aes(color = type, x = exposure_date, y = value/60)) + 
  geom_line(size = 1) +
  geom_point() +
  scale_x_datetime(breaks = "3 days", date_labels = "%d/%m") +
  saridr::theme_sarid() +
  labs(caption = "Data source: MOH GIS tracker @ bit.ly/corona_il\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") + 
  ggtitle("Exposure Duration",
          subtitle = "Mean and median exposure time") + 
  xlab("") + 
  ylab("Exposure Duration [minutes]") + 
  guides(color = guide_legend(""))  +
  geom_text(y = 380, color = "black", aes(label = n), angle = 90)

# Overall number of documented exposures ----------------------------------

exposure_files_raw %>% 
  count(exposure_date) %>% 
  ggplot(aes(x = exposure_date, y = n)) + 
  geom_line() +
  geom_point() +
  scale_x_datetime(breaks = "3 days", date_labels = "%d/%m", minor_breaks = "1 day") +
  saridr::theme_sarid() +
  labs(caption = "Data source: MOH GIS tracker @ bit.ly/corona_il\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") + 
  ggtitle("Total documented exposures") + 
  xlab("") + 
  ylab("Number of documented exposures")

# Times of exposures ------------------------------------------------------
# create a tile plot with the % exposures out of the day's total per each hour.

exposure_per_date_total <- exposure_files_raw %>% 
  count(exposure_date) %>% 
  mutate(rounded_date = lubridate::floor_date(exposure_date, unit = "days")) %>% 
  mutate(rounded_date_chr = as.character(rounded_date)) %>% 
  filter(rounded_date >= "2020-03-01") %>% 
  mutate(period_week = factor(floor_date(ymd(rounded_date_chr), unit = "week")) %>% 
           as.numeric %>% 
           paste0("w", .)) %>% 
  select(rounded_date_chr, n)
  
exposure_per_week <- exposure_per_date_total %>% 
  group_by(period_week) %>% 
  summarize(n = sum(n))

exposures_number <- tibble(exposure_time = seq(as.POSIXct("2020-03-01 00:00:00"), 
                                               as.POSIXct("2020-03-28 00:00:00"),
                                               by = "1 hour")) %>% 
  mutate(num_exposures = map_dbl(exposure_time, ~{
    exposure_files_raw %>% 
      filter(exposure_start <= .x & .x <= exposure_end) %>% 
      NROW() 
    }
  )
  ) %>% 
  mutate(rounded_date = lubridate::floor_date(exposure_time, unit = "days")) %>% 
  mutate(rounded_date_chr = as.character(rounded_date)) %>% 
  left_join(exposure_per_date_total, by = "rounded_date_chr") %>% 
  mutate(period_week = lubridate::floor_date(rounded_date, unit = "weeks")) %>% 
  mutate(period_week = factor(period_week) %>% as.numeric %>% paste0("w", .)) %>% 
  mutate(hour = lubridate::hour(exposure_time)) %>% 
  select(-rounded_date_chr) %>% 
  rename(total_exposures_for_day = n) %>% 
  mutate(percent_exposure = num_exposures/total_exposures_for_day) %>% 
  filter(total_exposures_for_day > 10) %>% 
  mutate(weekday = weekdays(rounded_date)) %>% 
  mutate(weekend = ifelse(weekday %in% c("Friday", "Saturday"),
                          "Weekend",
                          "Workday"))

# per day
per_day_exposure_plot <- ggplot(exposures_number %>% filter(rounded_date <= "2020-03-23"), aes(x = hour, y = rounded_date, fill = percent_exposure)) + 
  geom_tile() + 
  scale_fill_viridis_c() +
  saridr::theme_sarid() +
  labs(caption = "Data source: MOH GIS tracker @ bit.ly/corona_il\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") + 
  ggtitle("Exposures per day") + 
  xlab("Hour") + 
  ylab("Day") + 
  scale_y_datetime(breaks = "7 days", minor_breaks = "1 day", date_labels = "%d/%m") + 
  guides(fill = guide_legend("Daily\nintensity"))

# per week
per_week_exposure_plot <- exposures_number %>% 
  group_by(period_week, hour) %>% 
  summarize(exposures_per_hour = sum(num_exposures)) %>% 
  left_join(exposure_per_week, by = "period_week") %>% 
  rename(total_exposures = n) %>% 
  mutate(percent_of_exposures = exposures_per_hour / total_exposures) %>% 
  ggplot(aes(x = hour, y = percent_of_exposures, color = period_week)) + 
  geom_line() +
  saridr::theme_sarid() +
  labs(caption = "Data source: MOH GIS tracker @ bit.ly/corona_il\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") + 
  ggtitle("Exposure intensity as a function of hour") + 
  xlab("Hour") + 
  ylab("Intensity (# exposure/total for week)") + 
  guides(color = guide_legend("Week\n(in March)"))

# Combined plot
cowplot::plot_grid(per_day_exposure_plot,
                   per_week_exposure_plot)
