# Death demographics from Corona

library(tidyverse)

death_data <- read_csv("data/deaths/2020-04-11 - Corona deaths.csv",
                       skip = 1,
                       col_names = c("s_id",
                                     "age",
                                     "gender",
                                     "institution",
                                     "city")) %>% 
  mutate(age_groups = cut(age, c(min(age, na.rm = T) - 1, 50, 60, 70, 80, 90, max(age, na.rm = T))))

age_distribution <- death_data %>% 
  saridr::prop(age_groups, leave_n = T) %>% 
  ggplot(aes(x = age_groups, y = n4prop)) + 
  geom_col(fill = "#40b3f6") +
  saridr::theme_sarid() + 
  ylab("Cases") + 
  xlab("Age group") + 
  geom_label(aes(label = paste0(n4prop, " (", round(prop*100), "%)"))) +
  ggtitle("Deaths from Corona in Israel", subtitle = "Last updated 11th Apr 2020") + 
  labs(caption = "Data source: MOH Telegram reports @ https://t.me/MOHreport/3884\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il")

age_gender_distribution <- death_data %>% 
  group_by(age_groups) %>% 
  saridr::prop(gender, leave_n = T) %>% 
  ggplot(aes(x = age_groups, y = prop, fill = gender)) + 
  geom_col(aes(fill = gender), position = position_fill()) +
  geom_label(aes(label = paste0(round(prop*100), "%")), show.legend = F, position = position_fill()) +
  saridr::theme_sarid() + 
  scale_fill_manual(values = c("נקבה" =
                                 "#f1d682",
                               "זכר"=
                                 "#9d65ea")) + 
  scale_y_continuous(labels = scales::percent_format(1)) +
  ylab("Cases") + 
  xlab("Age group") + 
  ggtitle("Deaths from Corona in Israel - by gender", subtitle = "Last updated 11th Apr 2020") + 
  labs(caption = "Data source: MOH Telegram reports @ https://t.me/MOHreport/3884\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il")

cowplot::plot_grid(age_distribution, age_gender_distribution)


# Death rate using demographics/morbidity ---------------------------------

# Morbidity data pulled from covid19data.co.il github repository, based on MOH telegram reports.
# File pulled on the 2020-04-11 (from github history)

morbidity_11apr <- read_csv("data/age_distribution/2020-04-11_age_distribution.csv") %>% 
  rename(age_group = Age,
         total_confirmed = Count) %>% 
  select(-per_100k) %>% 
  mutate(age_group = ifelse(str_detect(age_group, "Unknown"),
                            NA,
                            age_group))
  
morbidity_and_death <- death_data %>% 
  mutate(age_group = cut(age, breaks = c(0, 9, 19, 29, 39, 49, 59, 69, 79, max(age, na.rm = T)))) %>%
  mutate(age_group = recode_factor(age_group,
                                 "(29,39]" = "20-39",
                                 "(39,49]" = "40-49",
                                 "(49,59]" = "50-59",
                                 "(59,69]" = "60-69",
                                 "(69,79]" = "70-79",
                                 "(79,98]" = "80+")) %>% 
  count(age_group, name = "deaths") %>% 
  right_join(morbidity_11apr, by = "age_group") %>% 
  mutate(deaths = ifelse(is.na(deaths), 0, deaths)) %>% 
  mutate(death_rate = deaths/total_confirmed)
  
# As a bar plot
death_rate <- morbidity_and_death %>% 
  ggplot(aes(y = death_rate, x = age_group)) + 
  geom_col(fill = "#40b3f6") + 
  geom_text(aes(label = paste0(round(death_rate*100), "%\n(",deaths, "/", total_confirmed, ")")), y = 0.16) +
  coord_cartesian(ylim = c(0, 0.17)) +
  saridr::theme_sarid() + 
  scale_y_continuous(labels = scales::percent_format(1)) +
  ylab("Mortality rate") + 
  xlab("Age group") + 
  ggtitle("Death rate from Corona in Israel - by age groups", subtitle = "A naive estimation (deaths/confirmed cases), last updated 11th Apr 2020") + 
  labs(caption = "Data source: MOH Telegram reports @ https://t.me/MOHreport/3884\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il")

# As a bubble chart
death_rate_bubble <- morbidity_and_death %>% 
  ggplot(aes(y = death_rate, x = age_group)) + 
  geom_point(color = "#40b3f6", aes(size = total_confirmed, y = death_rate)) + 
  geom_text(aes(label = paste0(round(death_rate*100,1), "%"), y = death_rate + 0.01)) +
  geom_text(aes(label = paste0("(",deaths, "/", total_confirmed, ")")), y = 0.18) +
  coord_cartesian(ylim = c(0, 0.185)) +
  saridr::theme_sarid() + 
  scale_y_continuous(labels = scales::percent_format(1)) +
  ylab("Mortality rate") + 
  xlab("Age group") + 
  guides(size = guide_legend("Confirmed cases\n(sample size)")) +
  ggtitle("Death rate from Corona in Israel - by age groups", subtitle = "A naive estimation (deaths/confirmed cases), last updated 11th Apr 2020") + 
  labs(caption = "Data source: MOH Telegram reports @ https://t.me/MOHreport/3884\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") +
  theme(legend.position = "bottom")
