# Death demographics from Corona

library(tidyverse)

death_data <- read_csv("data/deaths/2020-04-11 - Corona deaths.csv",
                       skip = 1,
                       col_names = c("s_id",
                                     "age",
                                     "gender",
                                     "institution",
                                     "city")) %>% 
  mutate(age_groups = cut(age, c(0, 50, 60, 70, 80, 90, max(age, na.rm = T))))

age_distribution <- death_data %>% 
  saridr::prop(age_groups, leave_n = T) %>% 
  ggplot(aes(x = age_groups, y = n4prop)) + 
  geom_col(fill = "#40b3f6") +
  saridr::theme_sarid() + 
  ylab("Cases") + 
  xlab("Age group") + 
  geom_label(aes(label = paste0(n4prop, " (", round(prop*100), "%)"))) +
  ggtitle("Deaths from Corona in Israel", subtitle = "Last updated 11th Apr 2020") + 
  labs(caption = "Data source: MOH Telegram reports @ https://t.me/MOHreport/3884\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il")

age_gender_distribution <- death_data %>% 
  group_by(age_groups) %>% 
  saridr::prop(gender, leave_n = T) %>% 
  ggplot(aes(x = age_groups, y = prop, fill = gender)) + 
  geom_col(aes(fill = gender), position = position_fill()) +
  geom_label(aes(label = paste0(round(prop*100), "%")), show.legend = F, position = position_fill()) +
  saridr::theme_sarid() + 
  scale_fill_manual(values = c("נקבה" =
                                 "#f1d682",
                               "זכר"=
                                 "#9d65ea")) + 
  scale_y_continuous(labels = scales::percent_format(1)) +
  ylab("Cases") + 
  xlab("Age group") + 
  ggtitle("Deaths from Corona in Israel - by gender", subtitle = "Last updated 11th Apr 2020") + 
  labs(caption = "Data source: MOH Telegram reports @ https://t.me/MOHreport/3884\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il")

cowplot::plot_grid(age_distribution, age_gender_distribution)
