# Statistics of city infections versus city population

library(tidyverse)

# Reads the csv data ----

infected_city_data <- read_csv("data/verified COVID19 by city.csv", skip = 1) %>% 
  select(2:3, 5:6, 8:9, 11:12)

arrange_to_tibble <- function(choose_vector){
  
  tibble(city = pull(infected_city_data, choose_vector + 1),
         infected = pull(infected_city_data, choose_vector) %>% as.numeric())
  
}

tidy_file <- map_df(c(1, 3, 5, 7), arrange_to_tibble) %>% 
  filter(!is.na(infected))

arranged <- bind_rows(tibble(city = infected_city_data$X3,
                             infected = infected_city_data[,1]))


# Reads the cbs settlement data ----

cbs <- readxl::read_xlsx("data/bycode2018.xlsx") %>% 
  filter(!is.na(population))


# Joining cbs and infected data -------------------------------------------

fuzzy_match <- function(original_str){
  which_location <- agrep(original_str, cbs$city)
  cbs$city[which_location[1]]
}

infected_concentration <- tidy_file %>% 
  mutate(best_approx_match = map_chr(city, fuzzy_match)) %>% 
  mutate(match_by = if_else(city %in% cbs$city, city, best_approx_match)) %>% 
  left_join(cbs,
            by = c("match_by" = "city")) %>% 
  distinct(match_by, .keep_all = T) %>% 
  mutate(proportion = infected/population) %>% 
  filter(!(city %in% 
             c("עופרה",
               "שומריה",
               "דבוריה",
               "נוף הגליל",
               "מסעודין אל-עזאזמה",
               "יהוד-מונוסון",
               "לא ידוע"))) %>% 
  arrange(desc(proportion)) %>% 
  select(-match_by) %>% 
  select(city, infected, population, proportion, everything()) %>% 
  mutate(population_clustered = cut(population, breaks = c(-.0001, 500, 1000, 10000, 1e6))) %>% 
  select(-best_approx_match)


# Export data -------------------------------------------------------------

openxlsx::write.xlsx(infected_concentration, "export/2020-03-27 - COVID19 - infected_vs_population.xlsx")


# Visualize data ----------------------------------------------------------

scatter_plot_infected <- ggplot(infected_concentration, aes(x = population, y = proportion)) + 
  geom_point() + 
  scale_x_log10() + 
  ggrepel::geom_label_repel(data = infected_concentration %>%
                              filter(proportion > 0.0045),
                            aes(label = city), alpha = 0.4) + 
  saridr::theme_sarid() + 
  ggtitle("Proportion of Corona infected (relative to settlement pop.)",
          subtitle = "Population axis provided in log-scale") + 
  xlab("Population") + 
  ylab("Proportion") + 
  labs(caption = "Data source: MOH publication\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il")

bar_plot_top15 <- ggplot(infected_concentration %>% slice(1:15) %>% 
                           arrange(proportion) %>% 
                           mutate(city = fct_inorder(city)),
                         aes(x = city, y = proportion)) + 
  coord_flip(ylim = c(0, 0.035)) +
  geom_col(fill = "lightblue") + 
  geom_label(nudge_y = -0.0005, aes(label = paste0(round(proportion*100,1), "% (", infected,"/", population,")"))) +
  saridr::theme_sarid() + 
  ggtitle("Proportion of Corona infected",
          subtitle = "Top 15 cities in Israel") + 
  xlab("") + 
  ylab("Proportion") + 
  scale_y_continuous(labels = scales::percent_format(1)) +
  labs(caption = "Data source: MOH publication\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il")
