# Files from the MOH repo in:
# https://data.gov.il/dataset/covid-19
# It is unclear if these files are refreshed into the same location or uploaded to a different location

library(tidyverse)


# Read the data ------------------------------------------------------------

isolations_raw <- readxl::read_excel("data/5-isolation-per-day-data.xlsx")
lab_tests_raw <- readxl::read_excel("data/corona_lab_tests_ver002.xlsx")
individuals_raw <- readxl::read_excel("data/corona_tested_individuals_ver_001.xlsx")


# Isolations by contact with confirmed ------------------------------------

# How many people are isolated by contact with a confirmed patient?
dardikman_hashkes <- read_csv("https://raw.githubusercontent.com/idandrd/israel-covid19-data/master/IsraelCOVID19.csv",
                              skip = 1,
                              col_names = c("reporting_date", "total", "new_cases", "moderate", "severe", "dead")) %>% 
  mutate(reporting_date = as.POSIXct(reporting_date, format = "%d/%m/%Y")) %>% 
  filter(!is.na(reporting_date)) %>% 
  select(reporting_date, total)

isolations <- isolations_raw %>% 
  rename(reporting_date = date) %>% 
  left_join(dardikman_hashkes) %>% 
  mutate(tot_lag1 = lag(total),
         tot_lag2 = lag(total, 2),
         tot_lag3 = lag(total, 3)) %>% 
  rename(tot_lag0 = total) %>%
  mutate_at(vars(starts_with("tot_lag")), 
            ~{new_contact_with_confirmed / .}) %>% 
  select(reporting_date, contains("tot_lag")) %>% 
  pivot_longer(cols = starts_with("tot_lag"), names_to = "lag", values_to = "ratio")
  
isolations_per_cases_all_lags <- ggplot(isolations, aes(x = reporting_date, y = ratio, color = lag))  + 
  geom_point() + 
  saridr::theme_sarid() + 
  scale_y_log10() + 
  stat_smooth(method = "lm", se = F) + 
  ggtitle("Log-ratio of quarantines/new cases, per day",
          subtitle = "Various lags examined (same-day, through 3 day lag)") +
  labs(caption = "Data source: MOH open data @ https://data.gov.il/dataset/covid-19\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il")

isolations_per_cases_lag1 <- ggplot(isolations %>% filter(lag == "tot_lag1"), 
                                    aes(x = reporting_date, y = ratio))  + 
  geom_point() + 
  saridr::theme_sarid() + 
  scale_y_log10() + 
  stat_smooth(method = "lm", se = F) + 
  ggtitle("Log-ratio of quarantines/new cases, per day",
          subtitle = "One day lag") +
  labs(caption = "Data source: MOH open data @ https://data.gov.il/dataset/covid-19\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") + 
  ylab("Ratio of\nquarantines/new cases") +
  xlab("Date")

# How symptoms correlate with corona result -------------------------------

individuals_corr <- individuals_raw %>% 
  mutate(corona_positive = ifelse(corona_result == "חיובי", 
                                  1, 0)) %>% 
  select(corona_positive, cough:head_ache) %>% 
  rename_all(~str_replace_all(., "_", " ")) %>% 
  mutate_all(as.numeric) %>% 
  as.matrix() %>% 
  cor(use = "pairwise.complete.obs")

ggcorrplot::ggcorrplot(individuals_corr, lab = T, type = "upper") +
  ggtitle("Correlations of symptoms and Corona detections",
          subtitle = "Sample of tests conducted by MOH") +
  saridr::theme_sarid() + 
  xlab("") + ylab("") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(caption = "Data source: MOH open data @ https://data.gov.il/dataset/covid-19\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il")

# Number of symptoms ----

num_symptoms_per_test <- individuals_raw %>% 
  select(cough:head_ache, test_indication) %>% 
  mutate(test_id = seq_along(cough)) %>% 
  pivot_longer(-c(test_indication, test_id), names_to = "symptom", values_to = "symptom_present") %>% 
  group_by(test_id, test_indication) %>% 
  summarize(num_symptoms = sum(as.numeric(symptom_present), na.rm = T))

ggplot(num_symptoms_per_test, aes(num_symptoms)) + 
  geom_histogram(bins = 6, fill = "lightblue") +
  saridr::theme_sarid() + 
  xlab("Symptoms") + ylab("") +
  ggtitle("Number of symptoms per Corona test, split by indication",
          subtitle = "Note that the y-axis varies. Most of the data is under 'other' indication") +
  labs(caption = "Data source: MOH open data @ https://data.gov.il/dataset/covid-19\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") +
  facet_wrap(~test_indication, scales = "free_y")

# Same chart by test results
individuals_raw %>% 
  select(cough:head_ache, corona_result) %>% 
  mutate(test_id = seq_along(cough)) %>% 
  pivot_longer(-c(corona_result, test_id), names_to = "symptom", values_to = "symptom_present") %>% 
  group_by(test_id, corona_result) %>% 
  summarize(num_symptoms = sum(as.numeric(symptom_present), na.rm = T)) %>% 
  ggplot(aes(num_symptoms)) + 
  geom_histogram(bins = 6, fill = "lightblue") +
  saridr::theme_sarid() + 
  xlab("Number of Symptoms") + ylab("Cases") +
  ggtitle("Number of symptoms per Corona test, split by test results",
          subtitle = "Note that the y-axis varies. Most of the data is under negative result (שלילי)") +
  labs(caption = "Data source: MOH open data @ https://data.gov.il/dataset/covid-19\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") +
  facet_wrap(~corona_result, scales = "free_y")



# Symptoms per positive ---------------------------------------------------

num_symptoms_per_positive <- individuals_raw %>% 
  filter(corona_result == "חיובי") %>% 
  select(cough:head_ache, test_indication) %>% 
  mutate(test_id = seq_along(cough)) %>% 
  pivot_longer(-c(test_indication, test_id), names_to = "symptom", values_to = "symptom_present") %>% 
  group_by(test_id, test_indication) %>% 
  summarize(num_symptoms = sum(as.numeric(symptom_present), na.rm = T))

num_symptoms_per_positive %>%
  ungroup() %>% 
  saridr::prop(num_symptoms)

# Comparison of symptoms for positive patients ----------------------------

# Distribution of number of symptoms

num_symptoms <- individuals_raw %>% 
  filter(corona_result == "חיובי") %>% 
  select(cough:head_ache, test_indication) %>% 
  mutate(test_id = seq_along(cough)) %>% 
  pivot_longer(-c(test_indication, test_id), names_to = "symptom", values_to = "symptom_present") %>% 
  group_by(test_id) %>% 
  summarize(symptom_present = sum(as.numeric(symptom_present), na.rm = T)) %>% 
  saridr::prop(symptom_present)

# comparison of symptoms by age

symptoms_by_age <- individuals_raw %>% 
  filter(corona_result == "חיובי") %>% 
  select(cough:head_ache, test_indication, age_60_and_above) %>% 
  mutate(test_id = seq_along(cough)) %>% 
  pivot_longer(-c(test_indication, test_id, age_60_and_above), names_to = "symptom", values_to = "symptom_present") %>% 
  filter(age_60_and_above != "NULL") %>% 
  group_by(symptom, age_60_and_above) %>% 
  summarize(symptom_present = mean(as.numeric(symptom_present), na.rm = T)) %>% 
  pivot_wider(id_cols = symptom, names_from = age_60_and_above, values_from = c(symptom_present)) %>% 
  rename(above60 = Yes,
         under60 = No)
  
# comparison of symptoms by gender controlling for age

symptoms_age_gender <- individuals_raw %>% 
  filter(corona_result == "חיובי") %>% 
  select(cough:head_ache, test_indication, gender, age_60_and_above) %>% 
  mutate(test_id = seq_along(cough)) %>% 
  pivot_longer(-c(test_indication, test_id, gender, age_60_and_above), names_to = "symptom", values_to = "symptom_present") %>% 
  filter(gender != "NULL", age_60_and_above != "NULL") %>% 
  group_by(symptom, gender, age_60_and_above) %>% 
  summarize(symptom_present = mean(as.numeric(symptom_present), na.rm = T),
            total = n()) %>% 
  mutate(age_group = case_when(age_60_and_above == "Yes" ~ "Above 60",
                               age_60_and_above == "No" ~ "Under 60")) %>% 
  ungroup() %>% 
  mutate(symptom = str_replace_all(symptom, fixed("_"), " ")) %>% 
  mutate(age_gender_group = case_when(age_group == "Above 60" & gender == "זכר" ~
                                        "60+ male",
                                      age_group == "Under 60" & gender == "זכר" ~
                                        "<60 male",
                                      age_group == "Above 60" & gender == "נקבה" ~
                                        "60+ female",
                                      age_group == "Under 60" & gender == "נקבה" ~
                                        "<60 female"))

# comparison between males and females in every age group

ggplot(symptoms_age_gender, 
       aes(x = symptom, fill = gender, y = symptom_present)) + 
  geom_col(position = "dodge") + 
  facet_wrap(~ age_group) +
  saridr::theme_sarid() + 
  xlab("Symptoms") + ylab("Proportion [%]") +
  scale_y_continuous(labels = scales::percent_format(1)) +
  ggtitle("Symptom prevalence - Confirmed Corona Cases in Israel") +
  labs(caption = "Data source: MOH open data @ https://data.gov.il/dataset/covid-19\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") + 
  coord_flip() + 
  geom_label(aes(label = paste0(round(symptom_present*100), "%")), position = position_dodge(1), show.legend = F)

# comparison between age in every gender

ggplot(symptoms_age_gender, 
       aes(x = symptom, fill = age_group, y = symptom_present)) + 
  geom_col(position = "dodge") + 
  facet_wrap(~ gender) +
  saridr::theme_sarid() + 
  xlab("Symptoms") + ylab("Proportion [%]") +
  scale_y_continuous(labels = scales::percent_format(1)) +
  ggtitle("Symptom prevalence - Confirmed Corona Cases in Israel") +
  labs(caption = "Data source: MOH open data @ https://data.gov.il/dataset/covid-19\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") + 
  coord_flip() + 
  geom_label(aes(label = paste0(round(symptom_present*100), "%")), position = position_dodge(1), show.legend = F)

# A unifying chart comparing all groups
ggplot(symptoms_age_gender %>% 
         mutate(symptom = str_wrap(symptom, width = 10)) %>% 
         mutate(age_gender_group = paste0(age_gender_group, "\n(n=", total, ")")), 
       aes(x = symptom, fill = age_gender_group, y = symptom_present)) + 
  geom_col(position = "dodge") + 
  saridr::theme_sarid() + 
  xlab("Symptoms") + ylab("Proportion [%]") +
  scale_y_continuous(labels = scales::percent_format(1)) +
  ggtitle("Symptom prevalence - Confirmed Corona Cases in Israel") +
  labs(caption = "Data source: MOH open data @ https://data.gov.il/dataset/covid-19\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") + 
  geom_text(aes(label = paste0(round(symptom_present*100), "%"), y = symptom_present + 0.05), 
            position = position_dodge(1), show.legend = F) + 
  coord_flip() +
  scale_fill_brewer(palette = "Set2") + 
  guides(fill = guide_legend("Gender, age", keyheight = 2.5))

  