# Files from the MOH repo in:
# https://data.gov.il/dataset/covid-19
# It is unclear if these files are refreshed into the same location or uploaded to a different location

library(tidyverse)


# Read the data ------------------------------------------------------------

isolations_raw <- readxl::read_excel("data/5-isolation-per-day-data.xlsx")
lab_tests_raw <- readxl::read_excel("data/corona_lab_tests_ver002.xlsx")
individuals_raw <- readxl::read_excel("data/corona_tested_individuals_ver_001.xlsx")


# Isolations by contact with confirmed ------------------------------------

# How many people are isolated by contact with a confirmed patient?
dardikman_hashkes <- read_csv("https://raw.githubusercontent.com/idandrd/israel-covid19-data/master/IsraelCOVID19.csv",
                              skip = 1,
                              col_names = c("reporting_date", "total", "new_cases", "moderate", "severe", "dead")) %>% 
  mutate(reporting_date = as.POSIXct(reporting_date, format = "%d/%m/%Y")) %>% 
  filter(!is.na(reporting_date)) %>% 
  select(reporting_date, total)

isolations <- isolations_raw %>% 
  rename(reporting_date = date) %>% 
  left_join(dardikman_hashkes) %>% 
  mutate(tot_lag1 = lag(total),
         tot_lag2 = lag(total, 2),
         tot_lag3 = lag(total, 3)) %>% 
  rename(tot_lag0 = total) %>%
  mutate_at(vars(starts_with("tot_lag")), 
            ~{new_contact_with_confirmed / .}) %>% 
  select(reporting_date, contains("tot_lag")) %>% 
  pivot_longer(cols = starts_with("tot_lag"), names_to = "lag", values_to = "ratio")
  
isolations_per_cases_all_lags <- ggplot(isolations, aes(x = reporting_date, y = ratio, color = lag))  + 
  geom_point() + 
  saridr::theme_sarid() + 
  scale_y_log10() + 
  stat_smooth(method = "lm", se = F) + 
  ggtitle("Log-ratio of quarantines/new cases, per day",
          subtitle = "Various lags examined (same-day, through 3 day lag)") +
  labs(caption = "Data source: MOH open data @ https://data.gov.il/dataset/covid-19\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il")

isolations_per_cases_lag1 <- ggplot(isolations %>% filter(lag == "tot_lag1"), 
                                    aes(x = reporting_date, y = ratio))  + 
  geom_point() + 
  saridr::theme_sarid() + 
  scale_y_log10() + 
  stat_smooth(method = "lm", se = F) + 
  ggtitle("Log-ratio of quarantines/new cases, per day",
          subtitle = "One day lag") +
  labs(caption = "Data source: MOH open data @ https://data.gov.il/dataset/covid-19\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") + 
  ylab("Ratio of\nquarantines/new cases") +
  xlab("Date")

# How symptoms correlate with corona result -------------------------------

individuals_corr <- individuals_raw %>% 
  mutate(corona_positive = ifelse(corona_result == "חיובי", 
                                  1, 0)) %>% 
  select(corona_positive, cough:head_ache) %>% 
  rename_all(~str_replace_all(., "_", " ")) %>% 
  mutate_all(as.numeric) %>% 
  as.matrix() %>% 
  cor(use = "pairwise.complete.obs")

ggcorrplot::ggcorrplot(individuals_corr, lab = T, type = "upper") +
  ggtitle("Correlations of symptoms and Corona detections",
          subtitle = "Sample of tests conducted by MOH") +
  saridr::theme_sarid() + 
  xlab("") + ylab("") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(caption = "Data source: MOH open data @ https://data.gov.il/dataset/covid-19\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il")

# Number of symptoms ----

num_symptoms_per_test <- individuals_raw %>% 
  select(cough:head_ache, test_indication) %>% 
  mutate(test_id = seq_along(cough)) %>% 
  pivot_longer(-c(test_indication, test_id), names_to = "symptom", values_to = "symptom_present") %>% 
  group_by(test_id, test_indication) %>% 
  summarize(num_symptoms = sum(as.numeric(symptom_present), na.rm = T))

ggplot(num_symptoms_per_test, aes(num_symptoms)) + 
  geom_histogram(bins = 6, fill = "lightblue") +
  saridr::theme_sarid() + 
  xlab("") + ylab("") +
  ggtitle("Number of symptoms per Corona test, split by indication") +
  labs(caption = "Data source: MOH open data @ https://data.gov.il/dataset/covid-19\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") +
  facet_wrap(~test_indication, scales = "free_y")
