# Per city/settlement corona spread

settlements <- read_csv("https://raw.githubusercontent.com/idandrd/israel-covid19-data/master/CityData.csv") %>% 
  pivot_longer(cols = -c(City, Population), names_to = "date", values_to = "confirmed") %>% 
  janitor::clean_names() %>% 
  mutate(confirmed = ifelse(is.na(confirmed), 0, confirmed)) %>% 
  mutate(rate = confirmed/population) %>% 
  mutate(date = lubridate::dmy(date)) %>% 
  group_by(date) %>% 
  arrange(desc(rate)) %>% 
  mutate(relative_rank_rate = seq_along(rate)) %>% 
  arrange(desc(confirmed)) %>% 
  mutate(relative_rank_confirmed = seq_along(confirmed)) %>% 
  ungroup() %>% 
  mutate(label = if_else(relative_rank_rate <= 10 | relative_rank_confirmed <= 10, city, "")) %>% 
  arrange(city, date)

# static example
settlements %>% 
  filter(date == "2020-04-11") %>% 
  ggplot(aes(x = confirmed, y = rate)) +
  geom_point(alpha = 0.5, aes(size = log(population), color = rate)) + 
  geom_text(aes(label = label), position = position_nudge(x = 250))

# animation
library(gganimate)
animation <- settlements %>% 
  mutate(timestamp_date = date) %>% 
  ggplot(aes(x = confirmed, y = rate)) +
  geom_point(alpha = 0.8, aes(size = log(population), color = rate)) + 
  geom_text(aes(label = label), position = position_nudge(x = 250)) +
  saridr::theme_sarid() + 
  scale_y_continuous(labels = scales::percent_format()) +
  scale_color_continuous(labels = scales::percent_format()) +
  ylab("Rate [%]") + 
  xlab("# Confirmed") + 
  guides(size = guide_legend("log(Pop.)"),
         color = guide_legend("rate")) +
  ggtitle("Corona spread within cities", subtitle = "Date: {closest_state}") + 
  labs(caption = "Data source: MOH Telegram reports, arranged by https://covid19data.co.il/\nGenerated by Sarid Research Institute: https://www.sarid-ins.co.il") +
  theme(legend.position = "right") +
  transition_states(date, transition_length = 1, state_length = 0) +
  view_follow()
 
animate(animation, rewind = FALSE, width = 700, height = 600)
anim_save("corona_spread_per_settlement.gif")
